### ISSUE TITLE
Crash when loading new file or wave.

### ISSUE THREAD

**Issue by MichealReed** [alexmercerind/flutter_audio_desktop#13]
Not sure the root cause of this yet. Secondary calls to load audio, files or waves will cause a crash.

**Comment by alexmercerind** [comment]
Hi there @MichealReed !
(Oh that's so formal 😅 )

I feel this should be resolved now.

Try building the example.
Calling load on same player instance, or different player instances even simultaneously should be fixed.

Thanks.

I'm yet to implement playlists, should be pure Dart side code.

Thanks for your incredible help.

(I'm yet to decide on waves...)
