### ISSUE TITLE
getting error massage

### ISSUE THREAD

**Issue by gnudles** [alexmercerind/flutter_audio_desktop#19]
great plugin, man!
I was waiting for something like that. finally desktop audio playback for desktops.
the thing is, I'm using linux and I get the following error:
Unhandled Exception: MissingPluginException(No implementation found for method init on channel flutter_audio_desktop)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)

which sounds very strange because I saw in your code that you do handle that message

**Edit:**
encountered right now that: https://github.com/flutter/flutter/issues/62006
maybe good point to start from

**Comment by gnudles** [comment]
oh I think I got it. you wrote "if" instead of "else if".
my local file was probably older from your latest revision.
I can see the bug is fixed in your latest revision. please update your plugin in pub.dev

**Comment by alexmercerind** [comment]
Yeah! I'll update pub.dev version with new Additions from @MichealReed. These new additions are added by him.
