### ISSUE TITLE
plans for migration for universal platform support? (for the community)

### ISSUE THREAD

**Issue by softmarshmallow** [alexmercerind/flutter_audio_desktop#2]
https://github.com/luanpotter/audioplayers/issues/489

Do you have plans on merging this project into [luanpotter/audioplayers](https://github.com/luanpotter/audioplayers)?

**Comment by alexmercerind** [comment]
Hi @softmarshmallow !
Why not!
I made this plugin for myself & shared it for other people on GitHub. As, at the moment, there is not any audio library for Flutter Windows & Linux... So I made one myself.
I will definitely love to provide my support to other plugins out there for adding Windows & Linux support.
It's all in C++ & same code compatible with both Linux & Windows.

**Comment by alexmercerind** [comment]
But I feel that it's not going to be easy. As C++ & it's libraries aren't most user friendly like other languages. My this project right now is very basic in functionality & just does what it says. I'll try to add more stuff in terms of functionality with time.

**Comment by alexmercerind** [comment]
@softmarshmallow, I'll be providing my support for [just_audio](https://github.com/ryanheise/just_audio) first... as I talked to him about this before & he's nice guy so.

I'm already using his [audio_service](https://github.com/ryanheise/audio_service) & [just_audio](https://github.com/ryanheise/just_audio). So, it will be kinda easier for me to deal.

**Comment by softmarshmallow** [comment]
Thanks alot! Great work. Me 18 also.. ha.
