### ISSUE TITLE
Support asset files

### ISSUE THREAD

**Issue by 12people** [alexmercerind/flutter_audio_desktop#20]
It seems like right now, only local files are supported, not asset files. (At the very least, I'm not able to get asset files working.)

Would you be willing to add asset file playing as a feature? Or, if this functionality exists already, could you add a mention to the README or the example project?

Thank you for this project!

**Comment by alexmercerind** [comment]
Okay... This issue is fixed under vnext branch.

Sorry for the delay.
I'm back to development.

**Comment by alexmercerind** [comment]
Now plugin supports assets.

Load assets into `AudioPlayer` as follows:

```dart
audioPlayer.load(
  await AudioSource.fromAsset(
    'assets/audio.MP3',
  ),
);
```

Supported on both Windows & Linux.
