### ISSUE TITLE
Multiple instances of AudioPlayer don't work

### ISSUE THREAD

**Issue by gkovac42** [alexmercerind/flutter_audio_desktop#23]
To one @MichealReed, as you seem to be missing my point and closing issues on wrong grounds repeatedlly. My problem is not with calling the load or play methods multiple times (these work just fine on 0.0.7), it is with instantiating 2 or more instances of the AudioPlayer with ids on 0.0.8, with or without new keyword. Under those circumstances the app will crash on startup before load / play is even called, with or without new keyword. Perhaps I'm wrong but this seems like an entirey separate issue than the one you keep refering to. Just thought I'd point the issue again, as @alexmercerind seems to care at least. I certainly don't anymore and will not be recommending this plugin to anyone.

**Comment by MichealReed** [comment]
Let me state again, this crash cannot be reproduced in the example (which uses multiple players) or in a personal project that uses 1,000 players. I did not close the last issue, but please avoid making more like this. You have provided little code, no information about your flutter version, and very little guidelines for reproduction. It seems you are trying to figure out how to properly use the library, and we welcome contributions for clarity in the readme when you accomplish this, but please know others have this working as is.

Please make a new issue, without the politics, and with proper information after you spend time learning from the example project we worked hard to produce.

**Comment by alexmercerind** [comment]
Hi there @gkovac42!

I know I'm late to inform you, but I'm back to development on this project.
Sorry, I was not involved in development too much back then.

Please consider trying out the plugin now.

All the issues, related to multiple instances or calling load twice etc. mentioned by you, should be fixed now.

Thanks,
alexmercerind.
