### ISSUE TITLE
Checked out github version today and got following error

### ISSUE THREAD

**Issue by syleishere** [alexmercerind/flutter_audio_desktop#28]
Building Windows application...
C:\flutter\musicplayer\windows\flutter\ephemeral\.plugin_symlinks\flutter_audio_desktop\audioplayer\audioplayer.hpp(7,10): fatal error C1083: Cannot open include file: 'miniaudio/miniaudio.h': No such file or directory [C:\flutter\musicplayer\build\windows\plugins\flutter_audio_desktop\flutter_audio_desktop_plugin.vcxproj]
Exception: Build process failed.

**Comment by alexmercerind** [comment]
Hi there @syleishere !
Sorry for the inconvenience.
It's not an error, it's because a file isn't checked into the version control.

A new version to pub.dev is just published, please try that out. (Not from GitHub)

Thanks.
Let me know how that goes for you.

**Comment by alexmercerind** [comment]
@syleishere 
👀 Did your issue get resolved?

**Comment by syleishere** [comment]
Nope this happening

**Comment by syleishere** [comment]
Building Windows application...
C:\flutter\musicplayer\windows\flutter\ephemeral\.plugin_symlinks\flutter_audio_desktop\audioplayer\audioplayer.hpp(7,10): fatal error C1083: Cannot open include file: 'miniaudio/miniaudio.h': No such file or directory [C:\flutter\musicplayer\build\windows\plugins\flutter_audio_desktop\flutter_audio_desktop_plugin.vcxproj]
Exception: Build process failed.

**Comment by syleishere** [comment]
I did change my dependency:
  flutter_audio_desktop: ^0.0.9
  #flutter_audio_desktop:
  #  git:
  #    url: https://github.com/alexmercerind/flutter_audio_desktop


but getting same error for some reason

**Comment by syleishere** [comment]
flutter_audio_desktop: ^0.0.9
  #DISABLED GIT
  #flutter_audio_desktop:
  #git:
  #url: https://github.com/alexmercerind/flutter_audio_desktop

**Comment by alexmercerind** [comment]
@syleishere please use the pub.dev version 0.1.0

**Comment by alexmercerind** [comment]
@syleishere 

```yaml
dependencies:
  ...
  flutter_audio_desktop: ^0.1.0
```

**Comment by syleishere** [comment]
That works, thank-you.

**Comment by alexmercerind** [comment]
pub.dev version is exactly same as GitHub version.

Glad to hear.
