### ISSUE TITLE
If you play long audio, the performance of the whole program will be greatly affected. I wonder if you have found this problem

### ISSUE THREAD

**Issue by JasonWULMS** [alexmercerind/flutter_audio_desktop#5]
If you play long audio, the performance of the whole program will be greatly affected. I wonder if you have found this problem

**Comment by alexmercerind** [comment]
@JasonWULMS 

The issue is fixed in the [vnext](https://github.com/alexmercerind/flutter_audio_desktop/tree/vnext) branch.

I'll inform you once, its ready.

**Comment by alexmercerind** [comment]
Hi there!

Now `miniaudio_engine` is used for streaming based playback.

Issue should be fixed now.
